gameofthree:
  game:
    over-game-at: 1
    min-number: 4
    max-number: 100
    ai-name: Ai
    player:
      max-players: 2
  wsconfig:
    endpoint: /game-of-three-websocket
# Spring h2 datasource config
spring:
  datasource:
    url: jdbc:h2:mem:gameofthree
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect